### PR TITLE
vimfiler variables refactoring

### PR DESCRIPTION
**Pull request by Shougo**

### CODE REVIEW

**Comment by Shougo** [comment]
This is big change.
Please test it.

**Comment by lambdalisue** [comment]
1. Open VimFilerExplorer
2. Select file and hit `e`

lead me the following error.

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
Error detected while processing function vimfiler#mappings#do_switch_action..<SNR>140_switch..vimfiler#mappings#_change_vim_current_dir:
line    1:
E121: Undefined variable: b:vimfiler
E15: Invalid expression: b:vimfiler
line    2:
E121: Undefined variable: vimfiler
E15: Invalid expression: vimfiler.source !=# 'file'
line   11:
E121: Undefined variable: vimfiler
E116: Invalid arguments for function fnameescape(vimfiler.current_dir)
E15: Invalid expression: fnameescape(vimfiler.current_dir)
"test/DateTime.vimspec" 861L, 25343C
```

**Comment by Shougo** [comment]
@lambdalisue Please provide the minimal .vimrc.  I will test it.

**Comment by lambdalisue** [comment]
oh. I thought it was issue of explorer. ok i'll try to make minimal.

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.2]
On 土, 11月 7, 2015 at 1:52 午後, Shougo/vimfiler.vim
<reply@reply.github.com>
wrote:
@lambdalisue [https://github.com/lambdalisue] Please provide the minimal .vimrc. I will test it.

—
Reply to this email directly or view it on GitHub
[https://github.com/Shougo/vimfiler.vim/pull/333#issuecomment-154620866] .[https://github.com/notifications/beacon/AAhWCJDBqwruYT8SlnI8KMczyectJ4-8ks5pDXsTgaJpZM4GY6g1.gif]

**Comment by Shougo** [comment]
Fixed.

**Comment by Shougo** [comment]
Merged.

**Comment by lambdalisue** [comment]
Ok I'll try again

**Pull request merged**
