### PR TITLE
Change to preserve scroll position whenever possible

### PR DESCRIPTION
**Pull request by svermeulen**

### CODE REVIEW

**Comment by Shougo** [comment]
Please explain the behavior more clearly.

**Comment by svermeulen** [comment]
I've been using vimfiler for awhile now and have noticed that many times the scroll position will change suddenly.  For example, when opening/closing directories or after deleting/renaming files, it will often jump around.  This is very jarring.

The call to vimfiler#helper#_set_cursor seems like it tries to address this by using 'zz' commands and similar, but winsaveview/winrestoreview works better because it will cause the screen to move around less.

**Comment by Shougo** [comment]
OK.  I will merge it experimentally.
But I may revert it.

**Comment by rafi** [comment]
@svermeulen thank you very much for this fix. The scroll-position is being kept **much better** now after opening a file. I still see vimfiler scroll-position offsetting sometimes, however less, when there is more than 1 split. Important to note that I'm using [vim-choosewin](https://github.com/t9md/vim-choosewin) - a fantastic window selector that vimfiler automatically integrates with for opening files.

**Comment by svermeulen** [comment]
No problem - happy to contribute  :)

**Pull request merged**
